Le_Domain='registerbot.klmpk.me'
Le_Alt='no'
Le_Webroot='no'
Le_PreHook=''
Le_PostHook=''
Le_RenewHook=''
Le_API='https://acme-v02.api.letsencrypt.org/directory'
Le_Keylength='ec-256'
Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/1504177846/234924893166'
Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/1504177846/234924893166'
Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/04f1c9d6b2c67ea81307928493adba8a3d42'
Le_CertCreateTime='1704635731'
Le_CertCreateTimeStr='2024-01-07T13:55:31Z'
Le_NextRenewTimeStr='2024-03-06T13:55:31Z'
Le_NextRenewTime='1709733331'
Le_RealCertPath=''
Le_RealCACertPath=''
Le_RealKeyPath='/etc/xray/xray.key'
Le_ReloadCmd=''
Le_RealFullChainPath='/etc/xray/xray.crt'
