AUTO_UPGRADE='1'
UPGRADE_HASH='afacdfcb95e063325d8f01ebc8daa57322307d92'
DEFAULT_ACME_SERVER='https://acme-v02.api.letsencrypt.org/directory'
USER_PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
